### ISSUE TITLE
install issue 

### ISSUE THREAD

**Issue by trackermb** [beallio/media-server-status#1]
Hi there have followed your install instructions but when i run ./**init**.py I get the error message

bash: ./**init**.py: Permission denied 

have tried running as root but still get he same issue.  Do you have any ideas what I'm doing wrong?

Thanks

**Comment by trackermb** [comment]
chmod u+x ./init.py seems to have fixed it but when I run 

sudo -u $USER gunicorn wsgi:application -b $INTERNAL_IP:$PORT --workers=5

or in my case 

sudo -u root gunicorn wsgi:application -b 10.0.1.18:7979 --workers=5

I get the following error message

[2016-01-03 00:52:39 +0000] [2720] [INFO] Starting gunicorn 19.4.3
[2016-01-03 00:52:39 +0000] [2720] [INFO] Listening at: http://10.0.1.18:7979 (2720)
[2016-01-03 00:52:39 +0000] [2720] [INFO] Using worker: sync
[2016-01-03 00:52:39 +0000] [2725] [INFO] Booting worker with pid: 2725
[2016-01-03 00:52:39 +0000] [2725] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    **import**(module)
ImportError: No module named wsgi
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    **import**(module)
ImportError: No module named wsgi
[2016-01-03 00:52:39 +0000] [2725] [INFO] Worker exiting (pid: 2725)
[2016-01-03 00:52:39 +0000] [2720] [INFO] Shutting down: Master
[2016-01-03 00:52:39 +0000] [2720] [INFO] Reason: Worker failed to boot.

Again any ideas what I'm missing and how to fix this 
Thanks in advance

**Comment by beallio** [comment]
Double check the PROJECT_DIR and VIRTUAL_ENV_DIR variables in the wsgi.py file point to the correct directories.  Depending on the structure of your project and/or virtual environments you may need to update how the script adds paths.  

In the sample wsgi.py file the script assumes the virtual enviroment is nested within PROJECT_DIR.

**Comment by trackermb** [comment]
This is above my knowledge level I just followed each step in the install script is there something else that i need to setup if so could you give me the scripts to it as I've never used Virtualenv before
